spring:
  datasource:
    url: jdbc:mysql://124.221.189.38:3306/sys_gps?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: _AAABBBccc1
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxIdle: 100
      maxActive: 200
      # 获取连接等待超时的时间
      maxWait: 30000
      # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除
      testWhileIdle: true
      #获取连接时候验证，会影响性能
      test-on-borrow: false
      validation-query: SELECT 1 FROM DUAL
      # 每30秒运行一次空闲连接回收器（默认-1）
      timeBetweenEvictionRunsMillis: 300000
      # 池中的连接空闲30分钟后被回收（默认30分钟）
      minEvictableIdleTimeMillis: 3000000
      # 在每次空闲连接回收器线程(如果有)运行时检查的连接数量（设置为和maxIdle一样）
      numTestsPerEvictionRun: 100

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss

mybatis-plus:
  configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 19009

jt-server:
  jt808:
    enable: true
    port:
      udp: 7611
      tcp: 7611
    media-file:
      path: D:/jt_data/media_file
    alarm-file:
      host: 127.0.0.1
      port: 7612

  alarm-file:
    enable: true
    port: 7612
    path: D:/jt_data/alarm_file